---
title: "Spatial Simulations with Shiny"
output: 
  html_document:
    self_contained: false
    runtime: shiny
---


```{r, include = FALSE}
library(INLA)
library(inlabru)
library(fmesher)
library(sf)
library(terra)
library(tidyverse)
library(tidyterra)
library(stars)
library(raster)
```

```{r, include = FALSE}
wd <- '~/OneDrive - University of Glasgow/PhD/0_simulations'
boundary <- st_read(paste0(wd, '/data/20240312_ROI_4326.shp')) |> 
  st_union() |> 
  st_transform(crs = 32650)
boundary_sp <- as(boundary, "Spatial")
# Land cover
landcover <- rast(paste0(wd, '/data/Landcover_AllClass.tif')) %>% project(crs(boundary)) %>% raster::crop(boundary)
boundary_extent <- extent(boundary_sp)
empty_raster <- raster(boundary_extent, res = 500, crs = crs(boundary_sp))
aligned_landcover <- terra::resample(landcover, rast(empty_raster), method = "near")
mask <- rasterize(vect(boundary), aligned_landcover)
hab_mask <- terra::mask(aligned_landcover, mask)
hab_mask <- hab_mask %>% filter(Landcover_AllClass < 99)
df <- as.data.frame(hab_mask, xy=T)
df$class <- factor(df$Landcover_AllClass)
df$class <- plyr::revalue(df$class, c("0"="Oil", "1"="Secondary", "2"="Primary", "3"="Plantation", "4"="Built"))
df$class <- relevel(factor(df$class), ref = "Primary")
df_sf <- st_as_sf(df, coords = c('x', 'y'), crs = 32650)
```

```{r, include = FALSE}
k = 12
rho = 0.3
beta <- c(0, 0.4567584, 1.5648494, 1.0986123, 1.8282377)
sigma <- 0.5
variance <- sigma^2
alpha <- 2
range <- 1
n <- 12
kappa <- sqrt(8 * (alpha - 1)) / range
theta <- c(-0.5 * log(4 * pi * variance * kappa^2), log(kappa))
seed <- 1234
```


Column {.sidebar}
--------------------------------------------------

```{r}
sliderInput("coff", "coff:", min = 1000, max = 10000, value = 1000)
sliderInput("mx_edge", "mx_edge:", min = 1000, max = 10000, value = c(2500, 5000))
sliderInput("range", "range:", min = 10, max = 1000, value = 10)
sliderInput("k", "k:", min = 1, max = 12, value = 12)
sliderInput("month", "month:", min = 1, max = 12, value = 12)
sliderInput("rho", "rho:", min = 0, max = 1, value = 0.3)
sliderInput("sigma", "sigma:", min = 0.1, max = 2, value = 0.5)
```

```{r, include = FALSE}
# Define server logic
simple_mesh <- reactive({
    max_edge <- input$mx_edge
    coff <- input$coff
    #mesh <- fm_mesh_2d(df_sf)
    #mesh <- fm_mesh_2d(df_sf, cutoff = as.numeric(coff))
    mesh <- fm_mesh_2d(df_sf, max.edge = as.numeric(max_edge), cutoff = as.numeric(coff))
    mesh
  })
```

```{r, include = FALSE}
  # Reactive expression to create the spatial field
  
spatial_field <- reactive({
  k <- input$k
  rho <- input$rho
  sigma <- input$sigma
  range <- input$range
  
  variance <- sigma^2
  kappa <- sqrt(8 * (alpha - 1)) / range
  theta <- c(log(range), log(sigma))
  seed <- 1234
  
  boundary_sp <- as(boundary, "Spatial")
  mask <- rasterize(vect(boundary), aligned_landcover)
  mesh <- simple_mesh()
  spde <- inla.spde2.matern(mesh, alpha = alpha)
  Q <- inla.spde2.precision(spde, theta = theta)
  
  true_field <- inla.qsample(n, Q, seed = seed)
  df_sf$field <- fm_evaluate(mesh, loc = df_sf, field = true_field)
  
  df_sf$field_AR1 <- df_sf$field 
  for (j in 2:n) {
    df_sf$field_AR1[, j] <- rho * df_sf$field_AR1[, j - 1] + sqrt(1 - rho^2) * df_sf$field[, j]  
  }
  
  df_sf
})
```

Column
--------------------------------------------------

```{r}
renderPlot({
  mesh <- simple_mesh()
  ggplot() +
    geom_fm(data = mesh)
})
```

```{r}
renderPlot({
  month <- input$month
  df_sf <- spatial_field()
  ggplot() +
    gg(df_sf, aes(fill = field_AR1[,month]), geom = "tile") +
    ggtitle('Anopheles count')+
    labs(fill = 'Value', x='', y='')+
    theme_minimal()+
    scale_fill_gradient(low = "white", high = "red")+
    theme(axis.text.x = element_blank(), axis.text.y = element_blank())
})

```


